### ISSUE TITLE
Revit Crash - Conflict with Enscape

### ISSUE THREAD

**Issue by mortennlund** [mcneel/rhino.inside-revit#529]
**Versions**
> Rhino.Inside: 1.4.8007.15883
> Rhino: 7.13.21348.13001
> Revit: 2021.1.4 (21.1.40.95)

**Describe the bug**
Full immediate surrender, and unexpected surrender of Revit to the "Report Crash"-interface when using RiR. No warning or anything 
The RhinoDotNetCrash.txt appears on the desktop after the crash, leads me to suspect its Rhino.Inside thats causing it. 

**To Reproduce**
No real way to reproduce it. Happens without any real interaction. 

**Additional context**
RhinoDotNetCrash.txt content
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at A.c7df263a9b37fff7c89f4dfbfe038d49a.ce1cc06bc9fd9b41cdcda7103d008bbe3(c6d8c98e4398d53a828be90c2f7f5c9b1 c6f3ebb09065aab8a38dcfc0ee6b0894c)
   at A.c7df263a9b37fff7c89f4dfbfe038d49a.c6d8c98e4398d53a828be90c2f7f5c9b1.c97ff677ca825aa1254f6b7ae7d529d7c(c03f6a5188365ec4cf5f4047b3562ed42 c1c886a952828727263aa9c57bfde33ce, Keys c0b7f1e58b9daf2e0cf89a1a1d8e281b9)
   at A.c7df263a9b37fff7c89f4dfbfe038d49a.c6d8c98e4398d53a828be90c2f7f5c9b1.c3e150560f66705be288600db01497f5a()
   at A.c7df263a9b37fff7c89f4dfbfe038d49a.c5e2de26f72570725c69d553de3d40a1c()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[END ERROR]

**Comment by mortennlund** [comment]
@eirannejad

**Comment by eirannejad** [comment]
Do you have Enscape installed? The call stack has obfuscated code which makes me think it's coming from Enscape.

**Comment by mortennlund** [comment]
@eirannejad Yes I have.. Enscape also fails to initialize on Rhino.Inside.Revit, but that has never been an issue before. I'll try and set load protect on Enscape but I can't seem to get the "isolate Rhino settings" to work in RiR so I have to set it for all Rhino instance, which will get annoying real quick. I'll give it a couple of days with the load protect on and report back.

**Comment by kike-garbo** [comment]
Hi @mortennlund,

Since Rhino 7.21 "Isolate settings" also isolate load protected plugins in Rhino, so now you can load protect a plugin inside Revit while keep it enabled in Rhino stand-alone.

**Comment by mortennlund** [comment]
@kike-garbo Great! Just updated both Rhino and RiR yesterday, and just tested and its working. I flagged the issue to the Enscape team as well and they seem to have changed something because I've been able to run RiR in an "unsafe" manner with no crashes. But this will make it SO MUCH easier to eliminate any issues with plugins causing RiR to crash. Thanks for the update.

**Comment by SpaceArchitecture** [comment]
Any updates on that matter ? Any successes with the latest updates ?
